# Generated by Django 3.0.3 on 2021-12-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='description',
            new_name='subcategory_description',
        ),
    ]
