# Generated by Django 3.0.3 on 2021-12-25 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211225_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(32767), django.core.validators.MinValueValidator(1)]),
        ),
    ]
