# Generated by Django 3.0.3 on 2021-12-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20211226_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.SmallIntegerField(default=10),
        ),
    ]
