# Generated by Django 3.0.3 on 2021-12-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(default='Default', max_length=255),
        ),
    ]
