# Generated by Django 3.0.3 on 2021-12-28 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20211226_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popularity_score',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(32767), django.core.validators.MinValueValidator(1)]),
        ),
    ]
