# Generated by Django 3.0.3 on 2021-12-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_ordered_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ordered_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
