# Generated by Django 3.0.3 on 2021-12-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='review',
            new_name='review_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='subject',
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='review_description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='review_images',
            field=models.ImageField(blank=True, upload_to='images/reviews'),
        ),
    ]
