# Generated by Django 3.0.3 on 2021-12-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20211229_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='rating',
            field=models.SmallIntegerField(null=True),
        ),
    ]
