# Generated by Django 3.0.3 on 2021-12-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_reviewrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='review_images',
            field=models.FileField(blank=True, upload_to='images/reviews'),
        ),
    ]
