# Generated by Django 3.0.3 on 2021-12-30 01:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20211230_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='ip',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='rating',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
