# Generated by Django 3.0.3 on 2021-12-30 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_productimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'productimages', 'verbose_name_plural': 'product images'},
        ),
    ]
