# Generated by Django 3.0.3 on 2021-12-31 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20211230_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('material', 'material'), ('color', 'color'), ('size', 'size'), ('gift', 'gift')], max_length=255),
        ),
    ]
