# Generated by Django 3.0.3 on 2021-12-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20211231_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_price',
            field=models.SmallIntegerField(default=0),
        ),
    ]
