# Generated by Django 3.0.3 on 2021-12-31 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_variation_variation_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='review_images',
        ),
        migrations.CreateModel(
            name='ReviewRatingImages',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='images/reviews')),
                ('review_rating', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='store.ReviewRating')),
            ],
        ),
    ]
