# Generated by Django 3.0.3 on 2022-01-02 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_auto_20211231_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='popularity_score',
            new_name='popularity',
        ),
    ]
