# Generated by Django 3.0.3 on 2022-01-04 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20220102_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='popularity',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(32767), django.core.validators.MinValueValidator(0)]),
        ),
    ]
