# Generated by Django 3.0.3 on 2022-01-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_auto_20220104_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='review_images',
            new_name='review_image',
        ),
    ]
