# Generated by Django 3.0.3 on 2021-12-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='category_description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
