# Generated by Django 3.0.3 on 2021-12-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20211227_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_gift_charge',
            field=models.SmallIntegerField(default=0),
        ),
    ]
