# Generated by Django 3.0.3 on 2021-12-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_cart_gift_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_delivery_charge',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_grand_total',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_subtotal',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_tax',
            field=models.SmallIntegerField(default=0),
        ),
    ]
