# Generated by Django 3.0.3 on 2022-01-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20211231_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_grand_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_tax',
            field=models.FloatField(default=0),
        ),
    ]
