# Generated by Django 3.0.3 on 2021-12-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gift_wrap_charge',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_charge',
            field=models.SmallIntegerField(null=True),
        ),
    ]
