# Generated by Django 3.0.3 on 2021-12-30 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211230_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='gift_wrap_charge',
        ),
    ]
