# Generated by Django 3.0.3 on 2022-01-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_gift_wrap_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_charge',
            field=models.SmallIntegerField(null=True),
        ),
    ]
